### ISSUE TITLE
Sharing your checkpoint?

### ISSUE THREAD

**Issue by yaseryacoob** [jychoi118/toward_spatial_unbiased#1]
Are you planning to share your check point?

thanks

**Comment by jychoi118** [comment]
Sorry for late reply. We shared our checkpoint in the updated README.
Or checkout the [link](https://drive.google.com/file/d/1LkLQJW5gycW6Xr-Vw8r2SFK-IBQrZvXp/view?usp=sharing)

**Comment by yaseryacoob** [comment]
Thanks, I got it. I wonder if you have trained on the 1024 FFHQ resolution? In the paper you mention the 512x512.
Thanks for sharing!

**Comment by jychoi118** [comment]
Unfortunately, we did not train on 1024. To clarify, MSPE (w/random resizing) for the multi-scale generation task learns to generate 512 by resizing PEs, but the discriminator is trained only on 256.

**Comment by yaseryacoob** [comment]
Thanks. I am little unsure that these ideas in the paper would scale to the level of detail that exist in 1024 images. This is why I am asking.
